/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
    nodes: {
        Base: THREE.SkinnedMesh
        RigPelvis: THREE.Bone
        RigLLegPlatform: THREE.Bone
        RigRLegPlatform: THREE.Bone
    }
    materials: {
        ['01 - Default']: THREE.MeshStandardMaterial
    }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>()
    const { nodes, materials } = useGLTF('stream-pixels-extension/objects/Character.glb') as GLTFResult
    return (
        <group ref={group} {...props} dispose={null}>
            <group>
                <group name="RootNode" userData={{ name: 'RootNode' }}>
                    <group
                        name="Dummy_Prop_Back"
                        position={[-292.01, -1.39, 0]}
                        rotation={[-Math.PI, 0, -Math.PI / 2]}
                        scale={[100, 100, 100]}
                        userData={{ name: 'Dummy Prop Back' }}
                    />
                    <group
                        name="Dummy_Prop_Right"
                        position={[635.81, 6.03, 619.51]}
                        rotation={[1.57, 0, -3.13]}
                        scale={[100, 100, 100]}
                        userData={{ name: 'Dummy Prop Right' }}
                    />
                    <group
                        name="Dummy_Prop_Head"
                        position={[-367.14, 0, 0]}
                        rotation={[-Math.PI, 0, -Math.PI / 2]}
                        scale={[100, 100, 100]}
                        userData={{ name: 'Dummy Prop Head' }}
                    />
                    <group
                        name="Dummy_Prop_Left"
                        position={[715.9, -6.42, 620.42]}
                        rotation={[-1.57, 0, -0.01]}
                        scale={[100, 100, 100]}
                        userData={{ name: 'Dummy Prop Left' }}
                    />
                    <group name="Armature" userData={{ name: 'Armature' }}>
                        <primitive object={nodes.RigPelvis} />
                        <primitive object={nodes.RigLLegPlatform} />
                        <primitive object={nodes.RigRLegPlatform} />
                    </group>
                    <group
                        name="RigRArmPalmGizmo"
                        position={[-51.88, 82.03, 0.01]}
                        rotation={[-1.16, -1.56, -1.15]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigRArmPalmGizmo' }}
                    />
                    <group
                        name="RigRArm2Gizmo"
                        position={[-35.74, 82.17, -0.08]}
                        rotation={[0.96, -1.56, -0.6]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigRArm2Gizmo' }}
                    />
                    <group
                        name="RigRArm1Gizmo"
                        position={[-19.11, 82.47, 0]}
                        rotation={[1.83, -1.55, 0.25]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigRArm1Gizmo' }}
                    />
                    <group
                        name="RigLArmPalmGizmo"
                        position={[51.88, 82.03, 0.01]}
                        rotation={[-1.16, 1.56, 1.15]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigLArmPalmGizmo' }}
                    />
                    <group
                        name="RigLArm2Gizmo"
                        position={[35.74, 82.17, -0.08]}
                        rotation={[0.96, 1.56, 0.6]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigLArm2Gizmo' }}
                    />
                    <group
                        name="RigLArm1Gizmo"
                        position={[19.11, 82.47, 0]}
                        rotation={[1.83, 1.55, -0.25]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigLArm1Gizmo' }}
                    />
                    <group
                        name="RigPelvisGizmo"
                        position={[0, 46.49, 0]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigPelvisGizmo' }}
                    />
                    <group
                        name="RigRibcageGizmo"
                        position={[0, 82.92, 0]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigRibcageGizmo' }}
                    />
                    <group
                        name="RigHeadGizmo"
                        position={[0, 123.67, 0]}
                        rotation={[-Math.PI / 2, 0, -Math.PI]}
                        scale={[1, 1, 1]}
                        userData={{ name: 'RigHeadGizmo' }}
                    />
                    <group name="Rig" rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 1]} userData={{ name: 'Rig' }} />
                    <skinnedMesh
                        name="Base"
                        material={materials['01 - Default']}
                        geometry={nodes.Base.geometry}
                        skeleton={nodes.Base.skeleton}
                        rotation={[-Math.PI / 2, 0, 0]}
                        userData={{ name: 'Base' }}
                    />
                </group>
            </group>
        </group>
    )
};

useGLTF.preload('stream-pixels-extension/objects/Character.glb')
